# Augmented Python Reference

This notebook **expands on** the [original shorter reference material](https://gamesbyjames.github.io/learn_python_with_andrej_karpathy/ak_zero_to_hero_python_reference.html) by diving deeper into Python concepts suitable for learners progressing from beginner to intermediate levels. It introduces practical tools and techniques commonly encountered in real-world programming, especially in data science and machine learning workflows—though we stick to pure Python and NumPy here, avoiding deep learning frameworks like TensorFlow or PyTorch.

All code examples use **pure Python + NumPy** to ensure broad applicability. You’re encouraged to **run each code cell** to see the outputs and experiment with modifications. To test your understanding, **quizzes** are sprinkled throughout with multiple-choice options separated by lines. Answers are provided in the [Answers](#answers) section at the end, linked back to each quiz for easy reference.

## Table of Contents
1. [Setup (Imports)](#setup)
2. [Advanced List Operations & Comprehensions](#list-comprehensions)
3. [NumPy Array Operations](#numpy)
4. [Functional Programming (map, filter, reduce, lambdas)](#functional)
5. [Object-Oriented Programming (OOP)](#oop)
6. [Decorators](#decorators)
7. [Context Managers](#context)
8. [Python Type Hints](#type-hints)
9. [Efficient Iteration (Generators, itertools, Batching)](#efficient-iteration)
10. [Error Handling (try/except)](#error-handling)
11. [Advanced String Formatting (f-strings)](#string-formatting)
12. [Conclusion](#conclusion)
13. [Answers](#answers)


<a id="setup"></a>
# 1. Setup (Imports)

Before diving into the examples, we need to import a few essential Python modules. Ensure you have **NumPy** installed (`pip install numpy`) as it’s critical for numerical operations in later sections. The imports below bring in tools for arrays (NumPy), functional programming (`reduce` from `functools`), timing (`time`), and type annotations (`List` from `typing`). This cell sets the stage for everything that follows.

In [2]:
import numpy as np
from functools import reduce
import time
from typing import List
print("Imports complete.")

Imports complete.


<a id="list-comprehensions"></a>
# 2. Advanced List Operations & Comprehensions

You’re likely familiar with basic list comprehensions like `[x+1 for x in some_list]` to transform a list. This section explores **advanced techniques** that go beyond the basics, offering concise yet powerful ways to manipulate data. These include:
- **Nested list comprehensions**: Handling multi-dimensional data, such as flattening a matrix.
- **Using `zip`**: Pairing elements from multiple lists for parallel iteration.
- **Unzipping with `zip(*...)`**: Reversing the pairing process to split data back apart.

These patterns are particularly useful in data preprocessing tasks—think preparing inputs for machine learning models—where you need to transform or restructure datasets efficiently.

In [3]:
# Example: Nested list comprehension to flatten a 2D list
# Here, 'matrix' is a list of lists (a 2D structure). The nested comprehension
# iterates over each sublist 'x' and then each element 'y' within it.
matrix = [[1, 2, 3], [4, 5, 6]]
flattened = [y for x in matrix for y in x]
print("Original matrix:", matrix)
print("Flattened list:", flattened)

Original matrix: [[1, 2, 3], [4, 5, 6]]
Flattened list: [1, 2, 3, 4, 5, 6]


**Parallel Iteration with `zip`**

The **`zip`** function pairs up elements from multiple iterables (like lists), creating tuples of corresponding items. This is handy for tasks like combining features or labels in datasets. You can also **unzip** paired data using `zip(*...)` to reverse the process, splitting the tuples back into separate sequences.

In [4]:
list1 = [1, 2, 3]
list2 = [10, 20, 30]

# Zipping combines the lists into pairs
paired = list(zip(list1, list2))
print("Zipped pairs:", paired)

# Using zip in a comprehension for element-wise operations
sum_list = [a + b for (a, b) in zip(list1, list2)]
print("Element-wise sums:", sum_list)

# Unzipping splits the pairs back into separate lists
nums, tens = zip(*paired)
print("Unzipped nums:", nums)  # Note: unzip returns tuples, not lists
print("Unzipped tens:", tens)

# Additional example: Zipping more than two lists
list3 = ['a', 'b', 'c']
triples = list(zip(list1, list2, list3))
print("Zipped triples:", triples)

Zipped pairs: [(1, 10), (2, 20), (3, 30)]
Element-wise sums: [11, 22, 33]
Unzipped nums: (1, 2, 3)
Unzipped tens: (10, 20, 30)
Zipped triples: [(1, 10, 'a'), (2, 20, 'b'), (3, 30, 'c')]


## **Quiz 1** ([Answer](#answer-1))

What will be the result of this code?
```python
matrix = [[1, 2], [3, 4], [5, 6]]
result = [y*2 for x in matrix for y in x if y % 2 == 1]
print(result)
```
Options:

A. `[2, 6, 10]`

B. `[2, 4, 6, 8, 10, 12]`

C. `[2, 6, 10, 12]`


[Back to top](#top)

<a id="numpy"></a>
# 3. NumPy Array Operations

NumPy is the backbone of numerical computing in Python, providing efficient multi-dimensional arrays and operations. This section covers key features you’ll encounter frequently:

- **Array creation**: Build arrays with `np.array`, `np.zeros`, `np.ones`, or other helpers.
- **Broadcasting**: Automatically align arrays of different shapes for arithmetic operations.
- **Slicing/Indexing**: Access parts of arrays, extended to multiple dimensions (e.g., rows, columns).
- **Reshaping**: Change an array’s shape without altering its data, crucial for data preparation.
- **Element-wise math**: Apply operations like addition, multiplication, or functions (e.g., `np.sin`) across all elements.

These tools are foundational for tasks like matrix computations in machine learning or scientific simulations.

In [5]:
# Broadcasting example
# Array 'a' is 2D (2 rows, 3 columns), while 'b' is 1D (3 elements).
# NumPy 'broadcasts' 'b' to match 'a’s rows, adding it to each.
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])
print("Array a:\n", a)
print("\nArray b:", b)
print("\nBroadcasted a + b:\n", a + b)

Array a:
 [[1 2 3]
 [4 5 6]]

Array b: [10 20 30]

Broadcasted a + b:
 [[11 22 33]
 [14 25 36]]


In [6]:
# Slicing and reshaping
# Slicing: ':' means all rows, ':2' means first two columns
subarray = a[:, :2]
print("First two columns of a:\n", subarray)

# Reshape to 3 rows, 2 columns (must match total elements: 6)
reshaped = a.reshape(3, 2)
print("\nReshaped a to 3x2:\n", reshaped)

# Flatten to 1D using -1 (infers size automatically)
flattened = a.reshape(-1)
print("\nFlattened a:\n", flattened)

# Additional example: Creating arrays from scratch
zeros = np.zeros((2, 3))
print("\nArray of zeros (2x3):\n", zeros)

First two columns of a:
 [[1 2]
 [4 5]]

Reshaped a to 3x2:
 [[1 2]
 [3 4]
 [5 6]]

Flattened a:
 [1 2 3 4 5 6]

Array of zeros (2x3):
 [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# Element-wise operations
print("Element-wise multiplication (a * 2):\n", a * 2)
print("Element-wise squaring (a ** 2):\n", a ** 2)
print("Element-wise sine (np.sin(a)):\n", np.sin(a))

# Another broadcasting example
# 'factors' is (2,1), broadcasted across 'a’s columns
factors = np.array([[2], [3]])  # shape (2,1)
scaled_rows = a * factors
print("\nScaled rows (broadcasted multiplication):\n", scaled_rows)

Element-wise multiplication (a * 2):
 [[ 2  4  6]
 [ 8 10 12]]
Element-wise squaring (a ** 2):
 [[ 1  4  9]
 [16 25 36]]
Element-wise sine (np.sin(a)):
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]

Scaled rows (broadcasted multiplication):
 [[ 2  4  6]
 [12 15 18]]


## **Quiz 2** ([Answer](#answer-2))

Suppose `X` is shape `(5,4)` and `v` is shape `(4,)`. If we do `Y = X + v`, what is `Y.shape` due to broadcasting?

Options:

A. `(5, 4)`

B. `(4, 5)`

C. `(5, 4, 4)`

D. Broadcasting is not possible.


[Back to top](#top)

<a id="functional"></a>
# 4. Functional Programming (map, filter, reduce, lambdas)

Python supports a functional programming style alongside list comprehensions, offering tools like `map`, `filter`, and `reduce`. These functions process iterables in a declarative way:

- **`map(func, iterable)`**: Applies `func` to each item, returning an iterator of results—think transforming data point-by-point.
- **`filter(func, iterable)`**: Keeps only items where `func(item)` is `True`, useful for selecting subsets.
- **`reduce(func, iterable)`**: Combines all items into a single value by repeatedly applying `func` (requires `from functools import reduce`).
- **`lambda`**: Defines small, anonymous functions inline, perfect for quick operations without a full `def`.

These are alternatives to loops or comprehensions, often seen in concise, readable codebases.

In [8]:
nums = [1, 2, 3, 4, 5]

# Map: Square each number
squares = list(map(lambda x: x**2, nums))
print("Squares:", squares)

# Filter: Keep even numbers
evens = list(filter(lambda x: x % 2 == 0, nums))
print("Evens:", evens)

# Reduce: Multiply all numbers together
product = reduce(lambda a, b: a * b, nums)
print("Product of all:", product)

# Additional example: Combining map and filter
odd_squares = list(map(lambda x: x**2, filter(lambda x: x % 2 == 1, nums)))
print("Squares of odds:", odd_squares)

Squares: [1, 4, 9, 16, 25]
Evens: [2, 4]
Product of all: 120
Squares of odds: [1, 9, 25]


## **Quiz 3** ([Answer](#answer-3))

Which snippet **also** produces `[2, 3, 4]` (the same result as `list(map(lambda x: x+1, [1, 2, 3]))`)?

Options:

A. `[x + 1 for x in [1, 2, 3]]`

B. `list(filter(lambda x: x+1, [1, 2, 3]))`

C. `for x in [1, 2, 3]: x+1`


[Back to top](#top)

<a id="oop"></a>
# 5. Object-Oriented Programming (OOP)

OOP in Python revolves around **classes**, which bundle data (attributes) and behavior (methods) into reusable objects. Core concepts include:
- **Inheritance**: A subclass inherits and extends a base class’s functionality.
- **Encapsulation**: Grouping related data and methods, with `_variable` convention signaling “private” (though not enforced).
- **Polymorphism**: Different classes can implement the same method name in unique ways, allowing flexible code.

OOP shines in modeling real-world systems or organizing complex codebases, like simulations or frameworks.

In [9]:
class Animal:
    def __init__(self, name):
        self.name = name
        self._energy = 100  # '_energy' suggests it’s internal

    def speak(self):
        print(f"{self.name} makes a noise.")

    def info(self):
        print(f"{self.name} has energy {self._energy}.")

class Dog(Animal):
    def speak(self):
        print(f"{self.name} says: Woof!")

class Cat(Animal):
    def speak(self):
        print(f"{self.name} says: Meow!")

# Polymorphism: same method call, different outputs
animals = [Dog("Buddy"), Cat("Whiskers"), Animal("Generic")]
for a in animals:
    a.speak()

animals[0].info()

Buddy says: Woof!
Whiskers says: Meow!
Generic makes a noise.
Buddy has energy 100.


## **Quiz 4** ([Answer](#answer-4))

When two subclasses (like `Dog` and `Cat`) each **override** `speak()`, and you call `animal.speak()`, it runs the class-specific method. This is called _____.

Options:

A. Inheritance

B. Encapsulation

C. Polymorphism

D. Abstraction


[Back to top](#top)

<a id="decorators"></a>
# 6. Decorators

A **decorator** is a function that wraps another function to modify or enhance its behavior, applied with the `@decorator_name` syntax above the function definition. Decorators are ideal for adding reusable functionality—like timing, logging, or input validation—across multiple functions without cluttering their core logic.

In [10]:
def timer(func):
    """A decorator that measures and reports execution time of 'func'."""
    def wrapper(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        end = time.time()
        print(f"Function '{func.__name__}' took {end - start:.4f} seconds")
        return result
    return wrapper

@timer
def compute_sum(n):
    total = 0
    for i in range(n):
        total += i
    return total

res = compute_sum(1000000)
print("Result =", res)

# Additional example: Applying to a simple function
@timer
def say_hello(name):
    return f"Hello, {name}!"

print(say_hello("Alice"))

Function 'compute_sum' took 0.0561 seconds
Result = 499999500000
Function 'say_hello' took 0.0000 seconds
Hello, Alice!


## **Quiz 5** ([Answer](#answer-5))

In Python, which symbol is used to apply a decorator like `@timer` above a function?

Options:

A. `@`

B. `#`

C. `def`

D. `*`


[Back to top](#top)

<a id="context"></a>
# 7. Context Managers

A **context manager** ensures setup and cleanup around a block of code, typically used with the `with` statement. It’s perfect for resource management—think files, locks, or database connections—guaranteeing cleanup (like closing a file) even if errors occur. The `with` syntax simplifies this over manual try/finally blocks.

In [11]:
# Writing and reading a file using context managers
data = "Some text data\nAnother line"
with open("example.txt", "w") as f:
    f.write(data)

with open("example.txt", "r") as f:
    content = f.read()
    print("File content:\n", content)

File content:
 Some text data
Another line


## **Quiz 6** ([Answer](#answer-6))

Why use `with open('data.txt', 'r') as f:` instead of `f = open('data.txt', 'r')`?

Options:

A. It automatically closes the file, even if errors occur.

B. It’s the only way to read files in Python.

C. It reads the file much faster.

D. No specific reason.


[Back to top](#top)

<a id="type-hints"></a>
# 8. Python Type Hints

Type hints are **optional annotations** (e.g., `x: int`, `def foo(arg: str) -> int`) that specify expected types for variables, function arguments, and return values. Introduced in Python 3.5+, they’re used by static type checkers like `mypy` or IDEs (e.g., PyCharm, VS Code) to catch type mismatches before runtime. However, Python itself **ignores them during execution** because it’s dynamically typed—type hints are documentation, not enforcement.

This means passing a value of the 'wrong' type won’t raise a type error automatically; errors only occur if the code’s logic fails (e.g., calling a method that doesn’t exist on the passed type). This section shows both correct usage and a deliberate misuse to illustrate this behavior.

In [20]:
from typing import List

def concatenate(words: List[str], sep: str = " ") -> str:
    """Join a list of strings with a separator, returning a single string.
    
    Args:
        words: A list of strings to join.
        sep: A string to insert between elements (default is a space).
    Returns:
        A single string with elements joined by 'sep'.
    """
    return sep.join(words)

# Correct usage: Both arguments match their type hints
print(concatenate(["deep", "learning"], sep="-"))  # Output: 'deep-learning'

# Incorrect usage: Passing an int for 'sep' violates the hint
# Type hints don’t stop this at runtime; it fails because int has no 'join' method
try:
    bad = concatenate(["number", "one"], sep=5)
    print("Result with wrong type:", bad)
except AttributeError as e:
    print(f"Runtime error: {e}")  # Output: 'int' object has no attribute 'join'

# Another example: Type hint ignored, but logic still works
def add(a: int, b: int) -> int:
    return a + b

print(add(3, 4))      # Works fine: 7
print(add(3.5, 4.5))  # Hint says int, but floats work too: 8.0

deep-learning
Runtime error: 'int' object has no attribute 'join'
7
8.0


## **Quiz 7** ([Answer](#answer-7))

True or False: *Python will raise a runtime error if you pass a value of the wrong type to a function that has type hints.*

Options:

A. True

B. False


[Back to top](#top)

<a id="efficient-iteration"></a>
# 9. Efficient Iteration (Generators, itertools, Batching)

When working with large or infinite datasets, **generators** save memory by yielding items one at a time instead of storing everything in a list. The `itertools` module (not fully explored here) offers additional tools like `cycle`, `chain`, or `combinations`. This section focuses on generators and a common use case: batching data, as seen in machine learning training loops.

In [14]:
def count_up_to(n):
    """Yield numbers from 1 to n, one at a time."""
    i = 1
    while i <= n:
        yield i
        i += 1

gen = count_up_to(5)
print("Generator created:", gen)  # Shows it’s a generator object
print("First value:", next(gen))  # Get the first item
print("Remaining values:")
for num in gen:  # Iterate over the rest
    print(num)

Generator created: <generator object count_up_to at 0x0000014AF1AB7C80>
First value: 1
Remaining values:
2
3
4
5


### Batching Example

Batching splits data into chunks, a technique used in mini-batch training for efficiency. The generator below yields slices of a list based on a batch size.

In [15]:
def batchify(data, batch_size):
    """Yield successive 'batch_size' chunks from 'data'."""
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]

dataset = list(range(1, 11))
for batch in batchify(dataset, 4):
    print(batch)

[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10]


## **Quiz 8** ([Answer](#answer-8))

What **keyword** inside a function makes it a generator?

Options:

A. yield

B. return

C. async

D. gen


[Back to top](#top)

<a id="error-handling"></a>
# 10. Error Handling (try/except)

Error handling with `try/except` lets your code recover from runtime issues gracefully, while `raise` lets you signal problems explicitly. Key components:

- **`try: ... except SomeError:`**: Catch specific exceptions like `ZeroDivisionError`.
- **`else:`**: Runs if no exception occurs, separating success logic.
- **`finally:`**: Always executes, useful for cleanup.
- **`raise`**: Throw custom exceptions for invalid states.

This is critical for robust programs, especially when dealing with user input or external resources.

In [16]:
def safe_divide(a, b):
    try:
        result = a / b
    except ZeroDivisionError:
        print("Error: cannot divide by zero!")
        result = None
    else:
        print("Division succeeded.")
    finally:
        print("Execution of safe_divide complete.")
    return result

print(safe_divide(10, 2))
print("---")
print(safe_divide(5, 0))

Division succeeded.
Execution of safe_divide complete.
5.0
---
Error: cannot divide by zero!
Execution of safe_divide complete.
None


In [17]:
def set_learning_rate(lr):
    if lr <= 0:
        raise ValueError(f"Learning rate must be positive, got {lr}")
    print(f"Learning rate set to {lr}")

set_learning_rate(0.01)
try:
    set_learning_rate(0)
except ValueError as e:
    print("Caught exception:", e)

Learning rate set to 0.01
Caught exception: Learning rate must be positive, got 0


## **Quiz 9** ([Answer](#answer-9))

Which snippet catches a **missing file** error?

Options:

A.

try:

    f = open('data.txt')

except FileNotFoundError:

    print('File missing')


B.

try:

    f = open('data.txt')

except KeyError:

    print('File missing')


C.

try:

    f = open('data.txt')

except ZeroDivisionError:

    print('File missing')


[Back to top](#top)

<a id="string-formatting"></a>
# 11. Advanced String Formatting (f-strings)

Introduced in Python 3.6, **f-strings** (`f"text {variable}"`) are a concise, readable way to embed expressions in strings. They support:

- **Format specifiers**: Control precision (e.g., `{x:.2f}` for 2 decimals).
- **Padding/alignment**: Zero-pad numbers (e.g., `{n:03d}`) or align text.
- **Expressions**: Compute values inline (e.g., `{x * 2}`).

F-strings are widely used for logging, reporting, or formatting outputs in a consistent style.

In [ ]:
epoch = 5
loss = 0.123456
print(f"Epoch {epoch} - Loss: {loss}")

value = 7.56789
print(f"value = {value}")
print(f"value to 2 decimal places = {value:.2f}")
print(f"value in scientific notation = {value:.1e}")

num = 42
print(f"number padded (width 5) = {num:05d}")

for e in range(1, 4):
    train_loss = 0.1 * e
    print(f"[Epoch {e:02d}] Loss = {train_loss:.3f}")

## **Quiz 10** ([Answer](#answer-10))

What does the following code print?
```python
value = 5
print(f"Value = {value:03d}")
```
Options:

A. `Value = 005`

B. `Value = 5  `

C. `Value = 0005`

D. `Value = 05`

## **Quiz 11** ([Answer](#answer-11))

What will `print(f'Loss: {0.456:.1f}')` output?

Options:

A. `Loss: 0.5`

B. `Loss: 0.46`

C. `Loss: 0.4`

D. `Loss: 0.456`


[Back to top](#top)

<a id="conclusion"></a>
# 12. Conclusion

This notebook has broadened your Python toolkit with concepts like:
- Advanced List Comprehensions for data transformation
- NumPy Array Operations for numerical efficiency
- Functional Programming (map, filter, reduce) for declarative coding
- OOP Basics for structured design
- Decorators for reusable enhancements
- Context Managers for resource safety
- Type Hints for code clarity
- Generators and Batching for memory-efficient iteration
- Error Handling for robustness
- Advanced String Formatting for polished outputs

These skills are stepping stones to mastering Python in data science, scripting, or even machine learning prep work. Keep this reference handy alongside the [original shorter guide](https://github.com/gamesbyjames/spanish-flash/blob/main/zero_to_hero_python_reference.ipynb) as you encounter these patterns in the wild!

[Back to top](#top)

<a id="answers"></a>
# 13. Answers

## <a id="answer-1"></a>Answer to Quiz 1 ([Back](#list-comprehensions))
Correct: **A. `[2, 6, 10]`** – The comprehension doubles only odd numbers (1, 3, 5) from the matrix due to the `if y % 2 == 1` filter.

## <a id="answer-2"></a>Answer to Quiz 2 ([Back](#numpy))
Correct: **A. `(5, 4)`** – Broadcasting extends `v` (shape `(4,)`) across each row of `X` (shape `(5, 4)`), keeping the result `(5, 4)`.

## <a id="answer-3"></a>Answer to Quiz 3 ([Back](#functional))
Correct: **A. `[x + 1 for x in [1, 2, 3]]`** – This comprehension matches the `map` operation, adding 1 to each element.

## <a id="answer-4"></a>Answer to Quiz 4 ([Back](#oop))
Correct: **C. Polymorphism** – Different classes provide unique `speak()` implementations under the same method name.

## <a id="answer-5"></a>Answer to Quiz 5 ([Back](#decorators))
Correct: **A. `@`** – The `@` symbol applies a decorator to a function.

## <a id="answer-6"></a>Answer to Quiz 6 ([Back](#context))
Correct: **A. It automatically closes the file, even if errors occur.** – The `with` statement ensures proper resource cleanup.

## <a id="answer-7"></a>Answer to Quiz 7 ([Back](#type-hints))
Correct: **B. False** – Type hints are for tools, not runtime enforcement.

## <a id="answer-8"></a>Answer to Quiz 8 ([Back](#efficient-iteration))
Correct: **A. yield** – `yield` turns a function into a generator.

## <a id="answer-9"></a>Answer to Quiz 9 ([Back](#error-handling))
Correct: **A** – `FileNotFoundError` is the exception for missing files.

## <a id="answer-10"></a>Answer to Quiz 10 ([Back](#string-formatting))
Correct: **A. `Value = 005`** – `:03d` pads `5` to three digits with zeros.

## <a id="answer-11"></a>Answer to Quiz 11 ([Back](#string-formatting))
Correct: **C. `Loss: 0.4`** – `.1f` rounds 0.456 to one decimal place, giving 0.4.

[Back to top](#top)